![Imgur](https://i.imgur.com/h4PPC71.png)
#**10-modul. Maʼlumotlarga ishlov berish. Fayllar va maʼlumotlar ombori**

#**10.25. Modul boʻyicha yakuniy amaliy vazifa**

**Amaliyotni bajargach, fayllar bilan ishlash, API va veb sahifalardan ma’lumot olish, SQL soʻrovlarini yozish va ma’lumotlar omboriga ma’lumot saqlash koʻnikmalariga ega boʻlasiz.**

#**Fayldan oʻqish va yozish**

#**1) CSV fayldan maʼlumotlarni o‘qish**
* https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv havolasidagi maʼlumotlarni `df` oʻzgaruvchisiga saqlang!
* `df` dan tasodifiy 10 ta qatorni ekranga chiqaring!

In [1]:
#javobni shu yerda yozing.
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv ")
df.sample(10)

             Date                   Country     Status  AQI Value
6362   2022-08-29                   Bolivia   Moderate         72
16439  2024-12-05                     Egypt  Unhealthy        170
15447  2024-10-10                Azerbaijan   Moderate         55
3298   2022-08-08                      Guam       Good          4
12444  2023-07-20                    Turkey   Moderate         94
7826   2022-09-08                   Lebanon   Moderate         76
1737   2022-07-28             French Guiana       Good         15
11525  2023-06-08                    Belize   Moderate         58
13510  2024-06-20  United States of America  Hazardous        359
5036   2022-08-20                    Norway       Good         30

#**2) CSV fayliga yozish**
* Quyidagi maʼlumotlardan dataframe yarating va uni `people_data.csv` fayliga saqlang.
```
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah", "Ivy", "Jack"],
    "Age": [25, 30, 35, 40, 28, 33, 38, 45, 29, 31],
    "City": ["Tashkent", "Samarkand", "Bukhara", "Andijan", "Nukus", "Khiva", "Namangan", "Fergana", "Jizzakh", "Termez"]
}
```
* Quyidagi maʼlumotlardan yana bir dataframe yarating va uni `people_data_2.csv` fayliga saqlang.
```
{
'Name': ['Alice', 'Bob', 'Charlie'],
'Age': [25, 30, 35]
}
```

In [2]:
#javobni shu yerda yozing.
data = {
  "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah", "Ivy", "Jack"],
  "Age": [25, 30, 35, 40, 28, 33, 38, 45, 29, 31],
  "City": ["Tashkent", "Samarkand", "Bukhara", "Andijan", "Nukus", "Khiva", "Namangan", "Fergana", "Jizzakh", "Termez"]
}
df = pd.DataFrame(data)
df.to_csv("people_data.csv")
print("File saved")

File saved

In [3]:
data2 = {
'Name': ['Alice', 'Bob', 'Charlie'],
'Age': [25, 30, 35]
}
df2 = pd.DataFrame(data2)
df2.to_csv("people_data_2.csv")
print("File 2 saved")

File 2 saved

#**3) HDF5 formati bilan ishlash**
* Yuqorida yaratgan dataframeʼlaringizni `people.h5` faylida saqlang.
* `people.h5` faylidagi barcha jadvallarni oʻqing!

In [4]:
#javobni shu yerda yozing.
with pd.HDFStore("people.h5") as store:
  store.put("data", df)
  store.put("data2", df2)

In [5]:
hdf = pd.HDFStore("people.h5")

for key in hdf.keys():
    df = hdf[key]
    print(f"\n{key}")
    print(df)

/data
      Name  Age       City
0    Alice   25   Tashkent
1      Bob   30  Samarkand
2  Charlie   35    Bukhara
3    David   40    Andijan
4      Eve   28      Nukus
5    Frank   33      Khiva
6    Grace   38   Namangan
7   Hannah   45    Fergana
8      Ivy   29    Jizzakh
9     Jack   31     Termez

/data2
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

#**4) JSON fayllar bilan ishlash**
1. Quyidagi maʼlumotlarni dataframe koʻrinishida oʻqing va uni `data.json` fayliga yozing!
```
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah", "Ivy", "Jack"],
    "Age": [25, 30, 35, 40, 28, 33, 38, 45, 29, 31],
    "City": ["Tashkent", "Samarkand", "Bukhara", "Andijan", "Nukus", "Khiva", "Namangan", "Fergana", "Jizzakh", "Termez"]
}
```

In [6]:
#javobni shu yerda yozing.
data = {
 "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah", "Ivy", "Jack"],
 "Age": [25, 30, 35, 40, 28, 33, 38, 45, 29, 31],
 "City": ["Tashkent", "Samarkand", "Bukhara", "Andijan", "Nukus", "Khiva", "Namangan", "Fergana", "Jizzakh", "Termez"]
}

df_new = pd.DataFrame(data)
df_new.to_json("data.json")

#**5) APIʼlar bilan ishlash**
1. Quyida berilgan API 17 mingdan ortiq kriptovalyutalarning dollarga nisbatan narxi haqidagi maʼlumotlarni saqlaydi. Siz esa endi:
  * API orqali barcha maʼlumotlarni yigʻib oling;
  * ularni dataframe koʻrinishida saqlang;
  * maʼlumotlar boshidan 5 ta qatorni ekranga chiqaring;
  * maʼlumotlar ichidan `bitcoin` ni izlab toping!

In [7]:
coins_url = "https://api.coingecko.com/api/v3/coins/list"
#javobni shu yerda yozing.
import requests
response = requests.get(coins_url)
coins_df = pd.DataFrame(response.json())
coins_df.head(10)
bitcoin = coins_df[coins_df['id'] == 'bitcoin']
bitcoin

           id symbol     name
2055  bitcoin    btc  Bitcoin

#**6) APIʼlar bilan ishlash**
1. Yuqorida berilgan kriptovalyuta maʼlumotlaridan `id` ustunini roʻyxat koʻrinishida saqlang va bu roʻyxatga `coin_ids` deb nom bering.
2. https://api.coingecko.com/api/v3/simple/price?ids={coin_ids}&vs_currencies=usd havolasi orqali kriptovalyutalarning `usd` ga nisbatini oling (birinchi 100 ta maʼlumotni olish yetarli).
3. 2-shartda berilgan link orqali olingan maʼlumotlarni dataframe koʻrinishida saqlang. Bunda uning indeksi va `usd` ustuni boʻlsin. `index` -> kriptovalyutalar nomi, `usd` -> narxi

#**💡Ishora:** linkdagi `{coin_ids}` oʻzgaruvchi sifatida yozilgan. Siz ham 1-shartda saqlagan `coin_ids` oʻzgaruvchingizni shu qismda yozib keting!

In [8]:
from urllib import request
# coin_ids = #Bu yerda kriptovalyutalar nomi saqlangan roʻyxat (list) boʻlishi kerak.
coin_ids = list(coins_df['id'][:100])
# price_url = f"https://api.coingecko.com/api/v3/simple/price?ids={coin_ids}&vs_currencies=usd"

ids_str = ",".join(coin_ids)
price_url = f"https://api.coingecko.com/api/v3/simple/price?ids={ids_str}&vs_currencies=usd"

price_response = requests.get(price_url)
price_data = price_response.json()

price_df = pd.DataFrame(price_data).T
price_df.columns = ['usd']

price_df.head()

                          usd
_                    0.006595
000-capital          0.000240
0chain               0.005881
0dog                 0.000015
0-knowledge-network  0.000006

#**7) Veb sahifadan oʻqish**
1. Pandas yordamida veb sahifadagi jadvalni yuklab oling.
2. Ma’lumotlarni dataframe ko‘rinishida chiqaring.
3. Agar sahifada bir nechta jadval bo‘lsa, eng muhimini tanlang.
4. Ma’lumotni tozalang (bo‘sh qatorlarni olib tashlang, kerakli ustunlarni tanlang).
5. Natijani CSV faylga saqlang.

***Eslatma: manba sifatida oʻzingiz istagan veb sahifani tanlang. Bu vazifada mustaqil izlanishni oʻrganasiz!***

In [9]:
#javobni shu yerda yozing.
url = "https://en.wikipedia.org/wiki/Samarkand"
tables = pd.read_html(url)
print(len(tables))

samarkand_climate = tables[2]
samarkand_climate.drop(samarkand_climate.tail(2).index, inplace=True)
samarkand_climate.to_csv("samarkand_climate.csv")
print("Saved")

14
Saved

# **Maʼlumotlar ombori bilan ishlash**

#**8) Maʼlumotlar omborini yuklash va ulanish**
1. https://github.com/alishermutalov/praktikum-datasets/blob/praktikum/chinook.db havolasi orqali maʼlumotlar omborini yuklab oling.
2. Yuklab olingan maʼlumotlar omboriga sqlite3 moduli yordamida **ulaning**.

In [29]:
!wget https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
!unzip "chinook.zip"

--2025-07-28 07:23:52--  https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
Resolving www.sqlitetutorial.net (www.sqlitetutorial.net)... 172.67.172.250, 104.21.30.141, 2606:4700:3037::ac43:acfa, ...
Connecting to www.sqlitetutorial.net (www.sqlitetutorial.net)|172.67.172.250|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 305596 (298K) [application/zip]
Saving to: ‘chinook.zip’

chinook.zip         100%[===================>] 298.43K  --.-KB/s    in 0.05s

2025-07-28 07:23:52 (6.14 MB/s) - ‘chinook.zip’ saved [305596/305596]

Archive:  chinook.zip
  inflating: chinook.db

In [30]:
#javobni shu yerda yozing.
import pandas as pd
import sqlite3 as sql

db = sql.connect("chinook.db")
cursor = db.cursor()

#**9) Maʼlumotlar omboriga soʻrov yuborish**
1. Jadvallar roʻyxatini koʻring. Ularning ichida `albums` jadvali boʻlsa, shu jadvaldagi barcha maʼlumotlarni (qatorlarni) ekranga chiqaring.
2. Qatorlar soni nechta ekanini aniqlab, uni ham ekranga chiqaring.
3.`albums` jadvalining ustunlari haqidagi maʼlumotlarni ekranga chiqaring.

In [31]:
#javobni shu yerda yozing.
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
cursor.fetchall()

[('albums',),
 ('sqlite_sequence',),
 ('artists',),
 ('customers',),
 ('employees',),
 ('genres',),
 ('invoices',),
 ('invoice_items',),
 ('media_types',),
 ('playlists',),
 ('playlist_track',),
 ('tracks',),
 ('sqlite_stat1',)]

In [32]:
cursor.execute("select count (*) from albums")
cursor.fetchone()

(347,)

In [33]:
cursor.execute("pragma table_info(albums);")
cursor.fetchall()

[(0, 'AlbumId', 'INTEGER', 1, None, 1),
 (1, 'Title', 'NVARCHAR(160)', 1, None, 0),
 (2, 'ArtistId', 'INTEGER', 1, None, 0)]

#**10) SQL to DataFrame**
1. `albums` jadvalini `pandas.DataFrame` ga oʻtkazing!

In [34]:
#javobni shu yerda yozing.
query = "select * from albums"
df_albums = pd.read_sql(query, db, index_col="AlbumId")
df_albums

                                                     Title  ArtistId
AlbumId
1                    For Those About To Rock We Salute You         1
2                                        Balls to the Wall         2
3                                        Restless and Wild         2
4                                        Let There Be Rock         1
5                                                 Big Ones         3
...                                                    ...       ...
343                                 Respighi:Pines of Rome       226
344      Schubert: The Late String Quartets & String Qu...       272
345                                    Monteverdi: L'Orfeo       273
346                                  Mozart: Chamber Music       274
347      Koyaanisqatsi (Soundtrack from the Motion Pict...       275

[347 rows x 2 columns]

#**11)**  `chinook.db` maʼlumotlar omboridan `tracks` jadvalining birinchi 10 ta qatorini ekranga chiqaring

#💡Ishora: LIMIT

In [35]:
#javobni shu yerda yozing.
pd.read_sql("select * from tracks limit 10", db, index_col="TrackId")

,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
TrackId,,,,,,,,
1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
2,Balls to the Wall,2,2,1,None,342562,5510424,0.99
3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99
6,Put The Finger On You,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",205662,6713451,0.99
7,Let's Get It Up,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",233926,7636561,0.99
8,Inject The Venom,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",210834,6852860,0.99
9,Snowballed,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",203102,6599424,0.99
10,Evil Walks,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",263497,8611245,0.99

#**12)**`tracks` jadvalidan faqat `Name`, `Composer` ustunlarini tanlab oling!

In [36]:
#javobni shu yerda yozing.
query = "select Name, Composer from tracks limit 10"
# pd.read_sql(query, db)

cursor.execute(query)
cursor.fetchall()

[('For Those About To Rock (We Salute You)',
  'Angus Young, Malcolm Young, Brian Johnson'),
 ('Balls to the Wall', None),
 ('Fast As a Shark', 'F. Baltes, S. Kaufman, U. Dirkscneider & W. Hoffman'),
 ('Restless and Wild',
  'F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. Dirkscneider & W. Hoffman'),
 ('Princess of the Dawn', 'Deaffy & R.A. Smith-Diesel'),
 ('Put The Finger On You', 'Angus Young, Malcolm Young, Brian Johnson'),
 ("Let's Get It Up", 'Angus Young, Malcolm Young, Brian Johnson'),
 ('Inject The Venom', 'Angus Young, Malcolm Young, Brian Johnson'),
 ('Snowballed', 'Angus Young, Malcolm Young, Brian Johnson'),
 ('Evil Walks', 'Angus Young, Malcolm Young, Brian Johnson')]

#**13) ORDER BY , DISTINCT**
* `tracks` jadvalidagi takrorlanmaydigan `GenreId` qiymatlarini oling.
* `tracks` jadvalidagi treklarni `Milliseconds` ustuni bo‘yicha kamayish tartibida saralang.

#💡Ishora: ORDER BY , DISTINCT

In [37]:
#javobni shu yerda yozing.
query = "select distinct GenreId from tracks"
# pd.read_sql(query, db)

cursor.execute(query)
cursor.fetchall()

[(1,),
 (2,),
 (3,),
 (4,),
 (5,),
 (6,),
 (7,),
 (8,),
 (9,),
 (10,),
 (11,),
 (12,),
 (13,),
 (14,),
 (15,),
 (16,),
 (17,),
 (18,),
 (19,),
 (20,),
 (21,),
 (22,),
 (23,),
 (24,),
 (25,)]

In [38]:
query = "select * from tracks order by Milliseconds desc"
pd.read_sql(query, db)

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,2820,Occupation / Precipice,227,3,19,None,5286953,1054423946,1.99
1,3224,Through a Looking Glass,229,3,21,None,5088838,1059546140,1.99
2,3244,"Greetings from Earth, Pt. 1",253,3,20,None,2960293,536824558,1.99
3,3242,The Man With Nine Lives,253,3,20,None,2956998,577829804,1.99
4,3227,"Battlestar Galactica, Pt. 2",253,3,20,None,2956081,521387924,1.99
...,...,...,...,...,...,...,...,...,...
3498,3304,Commercial 1,258,1,17,L. Muggerud,7941,319888,0.99
3499,178,Oprah,18,1,4,None,6635,224313,0.99
3500,170,A Statistic,18,1,4,None,6373,211997,0.99
3501,168,Now Sports,18,1,4,None,4884,161266,0.99
3502,2461,É Uma Partida De Futebol,200,1,1,Samuel Rosa,1071,38747,0.99

#**14) Filtering**
 * `invoices` jadvalidan `Total` summasi 10 dan katta bo‘lgan maʼlumotlarni tanlang.

# 💡Ishora: WHERE

In [39]:
#javobni shu yerda yozing.
query = "select * from invoices where Total > 10"
pd.read_sql(query, db, index_col="InvoiceId")

,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
InvoiceId,,,,,,,,
5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86
12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86
19,40,2009-03-14 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,13.86
26,19,2009-04-14 00:00:00,1 Infinite Loop,Cupertino,CA,USA,95014,13.86
33,57,2009-05-15 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,13.86
...,...,...,...,...,...,...,...,...
383,10,2013-08-12 00:00:00,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,13.86
390,48,2013-09-12 00:00:00,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,13.86
397,27,2013-10-13 00:00:00,1033 N Park Ave,Tucson,AZ,USA,85719,13.86
404,6,2013-11-13 00:00:00,Rilská 3174/6,Prague,None,Czech Republic,14300,25.86
411,44,2013-12-14 00:00:00,Porthaninkatu 9,Helsinki,None,Finland,00530,13.86

#**15) CREATE and INSERT**
* `chinook.db` maʼlumotlar omboriga `users` jadvali yarating. Jadval maydonlari (ustunlar):
  * `id`
  * `name`
  * `birth_date`
* Yaratilgan `users` jadvaliga quyidagi maʼlumotlarni qoʻshing:

    * ```
    [
    ('Alice', 25), ('Bob', 30), ('Charlie', 35), ('David', 28), ('Eve', 22),
    ('Frank', 40), ('Grace', 27), ('Hannah', 32), ('Ivy', 29), ('Jack', 31),
    ('Kevin', 33), ('Liam', 26), ('Mia', 24), ('Noah', 36), ('Olivia', 23),
    ('Peter', 39), ('Quinn', 37), ('Rachel', 34), ('Samuel', 41), ('Tina', 21)
]
 ```

#💡Ishora: CREATE TABLE, INSERT

In [52]:
#javobni shu yerda yozing.
db = sql.connect("chinook.db")
cursor = db.cursor()

query = """
create table if not exists users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(20),
  birth_date INT
);
"""

cursor.execute(query)
db.commit()

In [53]:
cursor.execute("select name from sqlite_master where type='table'")
cursor.fetchall()

[('albums',),
 ('sqlite_sequence',),
 ('artists',),
 ('customers',),
 ('employees',),
 ('genres',),
 ('invoices',),
 ('invoice_items',),
 ('media_types',),
 ('playlists',),
 ('playlist_track',),
 ('tracks',),
 ('sqlite_stat1',),
 ('users',)]

In [54]:
users_data = [
('Alice', 25), ('Bob', 30), ('Charlie', 35), ('David', 28), ('Eve', 22),
('Frank', 40), ('Grace', 27), ('Hannah', 32), ('Ivy', 29), ('Jack', 31),
('Kevin', 33), ('Liam', 26), ('Mia', 24), ('Noah', 36), ('Olivia', 23),
('Peter', 39), ('Quinn', 37), ('Rachel', 34), ('Samuel', 41), ('Tina', 21)
]

query = """
insert into users (name, birth_date) values(?, ?)
"""
cursor.executemany(query, users_data)
db.commit()

In [56]:
pd.read_sql("select * from users", db, index_col="id")

       name  birth_date
id
1     Alice          25
2       Bob          30
3   Charlie          35
4     David          28
5       Eve          22
6     Frank          40
7     Grace          27
8    Hannah          32
9       Ivy          29
10     Jack          31
11    Kevin          33
12     Liam          26
13      Mia          24
14     Noah          36
15   Olivia          23
16    Peter          39
17    Quinn          37
18   Rachel          34
19   Samuel          41
20     Tina          21

#**16) UPDATE and DELETE**
* `users` jadvalidagi Alice ismli foydalanuvchining yoshini yangilang.
* `users` jadvalidan Alice ismli foydalanuvchini o‘chiring.

In [65]:
#javobni shu yerda yozing.
cursor.execute("update users set birth_date = 26 where name='Alice';")
db.commit()

cursor.execute("select * from users where name='Alice';")
cursor.fetchall()

[(1, 'Alice', 26)]

In [69]:
# users jadvalidan Alice ismli foydalanuvchini o‘chiring.
cursor.execute("delete from users where name='Alice';")
db.commit()

cursor.execute("select * from users")
cursor.fetchall()

[(2, 'Bob', 30),
 (3, 'Charlie', 35),
 (4, 'David', 28),
 (5, 'Eve', 22),
 (6, 'Frank', 40),
 (7, 'Grace', 27),
 (8, 'Hannah', 32),
 (9, 'Ivy', 29),
 (10, 'Jack', 31),
 (11, 'Kevin', 33),
 (12, 'Liam', 26),
 (13, 'Mia', 24),
 (14, 'Noah', 36),
 (15, 'Olivia', 23),
 (16, 'Peter', 39),
 (17, 'Quinn', 37),
 (18, 'Rachel', 34),
 (19, 'Samuel', 41),
 (20, 'Tina', 21)]

#**17) f-string yordamida SQL komandalarini yozish**
* `customers` jadvalidan `FirstName` va `LastName` bo‘yicha qidiruv qiladigan f-string yozing.

In [81]:
#javobni shu yerda yozing.
query = "select * from customers"
df = pd.read_sql(query, db, index_col="CustomerId")
df.head()

,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
CustomerId,,,,,,,,,,,,
1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4

In [102]:
# id = df.index.values[0]
# first_name = df.at[id, 'FirstName']
# last_name = df.at[id, 'LastName']

first_name = "François"
last_name = "Tremblay"

query = f"select * from customers where FirstName='{first_name}' and LastName='{last_name}'"
pd.read_sql(query, db, index_col="CustomerId")

,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
CustomerId,,,,,,,,,,,,
3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3

#**18)  AND and OR operators**

* `invoices` jadvalidan `BillingCountry` Germaniya yoki Fransiya boʻlgan va `Total` summasi 5 dan katta bo‘lgan kerakli qatorlarni tanlang.

#💡Ishora: AND, OR

In [120]:
#javobni shu yerda yozing.
query = "SELECT * FROM invoices WHERE BillingCountry IN ('Germany', 'France')  AND Total > 5"
pd.read_sql(query, db)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86
1,19,40,2009-03-14 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,13.86
2,31,42,2009-05-07 00:00:00,"9, Place Louis Barthou",Bordeaux,None,France,33000,5.94
3,40,36,2009-06-15 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,13.86
4,52,38,2009-08-08 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,5.94
5,67,2,2009-10-12 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,8.91
6,74,40,2009-11-12 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,8.91
7,95,36,2010-02-13 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,8.91
8,117,41,2010-05-22 00:00:00,"11, Place Bellecour",Lyon,None,France,69002,13.86
9,129,43,2010-07-15 00:00:00,"68, Rue Jouvence",Dijon,None,France,21000,5.94
10,138,37,2010-08-23 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,13.86
11,150,39,2010-10-16 00:00:00,"4, Rue Milton",Paris,None,France,75009,5.94
12,172,41,2011-01-20 00:00:00,"11, Place Bellecour",Lyon,None,France,69002,8.91
13,193,37,2011-04-23 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,14.91
14,215,42,2011-07-30 00:00:00,"9, Place Louis Barthou",Bordeaux,None,France,33000,13.86
15,236,38,2011-10-31 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,13.86
16,241,2,2011-11-23 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,5.94
17,248,40,2011-12-24 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,5.94
18,269,36,2012-03-26 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,5.94
19,270,42,2012-03-29 00:00:00,"9, Place Louis Barthou",Bordeaux,None,France,33000,8.91
20,291,38,2012-06-30 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,8.91
21,313,43,2012-10-06 00:00:00,"68, Rue Jouvence",Dijon,None,France,21000,16.86
22,334,39,2013-01-07 00:00:00,"4, Rue Milton",Paris,None,France,75009,13.86
23,346,41,2013-03-02 00:00:00,"11, Place Bellecour",Lyon,None,France,69002,5.94
24,367,37,2013-06-03 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,5.94
25,368,43,2013-06-06 00:00:00,"68, Rue Jouvence",Dijon,None,France,21000,8.91
26,389,39,2013-09-07 00:00:00,"4, Rue Milton",Paris,None,France,75009,8.91

#**19) BETWEEN and LIKE**

* `invoices` jadvalidan `Total` summasi 5 dan 15 gacha bo‘lgan qatorlarni tanlang.
* `customers` jadvalidan ismi `A` harfi bilan boshlanadigan foydalanuvchilarni tanlang.

In [124]:
#javobni shu yerda yozing.
pd.read_sql("select * from invoices where Total between 5 and 15", db)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,3,8,2009-01-03 00:00:00,Grétrystraat 63,Brussels,None,Belgium,1000,5.94
1,4,14,2009-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
2,5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86
3,10,46,2009-02-03 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,5.94
4,11,52,2009-02-06 00:00:00,202 Hoxton Street,London,None,United Kingdom,N1 5LH,8.91
...,...,...,...,...,...,...,...,...,...
163,402,50,2013-11-05 00:00:00,C/ San Bernardo 85,Madrid,None,Spain,28015,5.94
164,403,56,2013-11-08 00:00:00,307 Macacha Güemes,Buenos Aires,None,Argentina,1106,8.91
165,409,29,2013-12-06 00:00:00,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,5.94
166,410,35,2013-12-09 00:00:00,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,8.91
167,411,44,2013-12-14 00:00:00,Porthaninkatu 9,Helsinki,None,Finland,00530,13.86

#**20) DataFrame to SQL**
* Quyidagi maʼlumotlardan dataframe yarating.
  ```
  sales_data = {
    "sale_id": list(range(1, 21)),  # 1 dan 20 gacha boʻlgan unikal IDʼlar
    "product_name": [
        "Laptop", "Smartphone", "Tablet", "Headphones", "Smartwatch",
        "Monitor", "Keyboard", "Mouse", "Printer", "Camera",
        "Speaker", "Game Console", "TV", "Router", "Power Bank",
        "Hard Drive", "USB Flash", "Graphics Card", "Microphone", "VR Headset"
    ],
    "quantity": [2, 5, 3, 10, 4, 6, 8, 12, 3, 5, 7, 9, 4, 2, 11, 6, 15, 1, 3, 2],
    "price": [1200, 800, 450, 200, 300, 500, 100, 50, 250, 700,
              150, 400, 1000, 90, 60, 110, 30, 1500, 80, 600],
    "sale_date": [
        "2025-03-01", "2025-03-02", "2025-03-03", "2025-03-04", "2025-03-05",
        "2025-03-06", "2025-03-07", "2025-03-08", "2025-03-09", "2025-03-10",
        "2025-03-11", "2025-03-12", "2025-03-13", "2025-03-14", "2025-03-15",
        "2025-03-16", "2025-03-17", "2025-03-18", "2025-03-19", "2025-03-20"
    ]
}
```
*Yuqoridagi maʼlumotlar asosida yaratgan dataframeʼingizdan SQL jadvali tuzing va uni `sales` deb nomlang.

In [126]:
#javobni shu yerda yozing.
sales_data = {
  "sale_id": list(range(1, 21)),  # 1 dan 20 gacha boʻlgan unikal IDʼlar
  "product_name": [
      "Laptop", "Smartphone", "Tablet", "Headphones", "Smartwatch",
      "Monitor", "Keyboard", "Mouse", "Printer", "Camera",
      "Speaker", "Game Console", "TV", "Router", "Power Bank",
      "Hard Drive", "USB Flash", "Graphics Card", "Microphone", "VR Headset"
  ],
  "quantity": [2, 5, 3, 10, 4, 6, 8, 12, 3, 5, 7, 9, 4, 2, 11, 6, 15, 1, 3, 2],
  "price": [1200, 800, 450, 200, 300, 500, 100, 50, 250, 700,
            150, 400, 1000, 90, 60, 110, 30, 1500, 80, 600],
  "sale_date": [
      "2025-03-01", "2025-03-02", "2025-03-03", "2025-03-04", "2025-03-05",
      "2025-03-06", "2025-03-07", "2025-03-08", "2025-03-09", "2025-03-10",
      "2025-03-11", "2025-03-12", "2025-03-13", "2025-03-14", "2025-03-15",
      "2025-03-16", "2025-03-17", "2025-03-18", "2025-03-19", "2025-03-20"
  ]
}

df = pd.DataFrame(sales_data)
df

    sale_id   product_name  quantity  price   sale_date
0         1         Laptop         2   1200  2025-03-01
1         2     Smartphone         5    800  2025-03-02
2         3         Tablet         3    450  2025-03-03
3         4     Headphones        10    200  2025-03-04
4         5     Smartwatch         4    300  2025-03-05
5         6        Monitor         6    500  2025-03-06
6         7       Keyboard         8    100  2025-03-07
7         8          Mouse        12     50  2025-03-08
8         9        Printer         3    250  2025-03-09
9        10         Camera         5    700  2025-03-10
10       11        Speaker         7    150  2025-03-11
11       12   Game Console         9    400  2025-03-12
12       13             TV         4   1000  2025-03-13
13       14         Router         2     90  2025-03-14
14       15     Power Bank        11     60  2025-03-15
15       16     Hard Drive         6    110  2025-03-16
16       17      USB Flash        15     30  2025-03-17
17       18  Graphics Card         1   1500  2025-03-18
18       19     Microphone         3     80  2025-03-19
19       20     VR Headset         2    600  2025-03-20

In [127]:
df.to_sql(con = db, name = 'sales', if_exists='replace', index = False)

20

In [130]:
cursor.execute("select name from sqlite_master where type='table'")
cursor.fetchall()

[('albums',),
 ('sqlite_sequence',),
 ('artists',),
 ('customers',),
 ('employees',),
 ('genres',),
 ('invoices',),
 ('invoice_items',),
 ('media_types',),
 ('playlists',),
 ('playlist_track',),
 ('tracks',),
 ('sqlite_stat1',),
 ('users',),
 ('sales',)]

In [131]:
pd.read_sql("select * from sales", db)

    sale_id   product_name  quantity  price   sale_date
0         1         Laptop         2   1200  2025-03-01
1         2     Smartphone         5    800  2025-03-02
2         3         Tablet         3    450  2025-03-03
3         4     Headphones        10    200  2025-03-04
4         5     Smartwatch         4    300  2025-03-05
5         6        Monitor         6    500  2025-03-06
6         7       Keyboard         8    100  2025-03-07
7         8          Mouse        12     50  2025-03-08
8         9        Printer         3    250  2025-03-09
9        10         Camera         5    700  2025-03-10
10       11        Speaker         7    150  2025-03-11
11       12   Game Console         9    400  2025-03-12
12       13             TV         4   1000  2025-03-13
13       14         Router         2     90  2025-03-14
14       15     Power Bank        11     60  2025-03-15
15       16     Hard Drive         6    110  2025-03-16
16       17      USB Flash        15     30  2025-03-17
17       18  Graphics Card         1   1500  2025-03-18
18       19     Microphone         3     80  2025-03-19
19       20     VR Headset         2    600  2025-03-20